[project]
name = "sam-not-perfect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "efficient-sam2",
]

[tool.uv.sources]
efficient-sam2 = { git = "https://github.com/alexzilligmm/efficient-sam2.git" }
